#!/usr/bin/env python2
# -*- coding: utf-8 -*-

import subprocess
import time
import sys


if __name__ == "__main__":

    cmd_str = ['python2','./repo', 'status', '-j1']
    proc = subprocess.Popen(cmd_str, stdout=subprocess.PIPE)
    output = proc.stdout.read()

    changedProjects = []
    project = None
    for line in output.split("\n"):

        #remove empty lines
        if not line:
            continue

        words = line.split(" ")

        if words[1]=="scripts/":
            project = None
            continue

        if words[0]=="project":
            project = words[1]
            #print "Project:", project
        else:
            #print "changed"
            if project and project not in changedProjects:
                changedProjects.append(project)


    if len(changedProjects) > 0:
        print("Updating projects: ",changedProjects)

        cmd = "pip3 install"
        for proj in changedProjects:
            cmd = cmd + " " + proj

        cmd = cmd + " --upgrade --no-deps"
        print(cmd, "\n")
        time.sleep(1)
        p = subprocess.Popen(cmd, shell=True)
        p.communicate()
        print("DONE")
        sys.exit(0)
    else:
        print("Nothing to update")