## WiSHFUL global control program config file

controller:
    name: "contiki_global_control"
    info: "Example Contiki global control program"
    dl: "tcp://172.16.16.3:8990"
    ul: "tcp://172.16.16.3:8989"

modules:
    discovery:
        module : wishful_module_discovery_pyre
        class_name : PyreDiscoveryControllerModule
        kwargs: {"iface":"eno1", "groupName":"wishful_contiki", "downlink":"tcp://172.16.16.3:8990", "uplink":"tcp://172.16.16.3:8989"}
