## WiSHFUL Controller's config file

parameters:
  ad_address: "172.16.16.9"
  controllerName: "WIPLUS_LTE_U_DETECTOR"

controller:
    name: "wiplus"
    info: "WiPLUS LTE-U Detector"
    dl: "tcp://172.16.16.1:8990"
    ul: "tcp://172.16.16.1:8989"
