## WiSHFUL Controller's config file

parameters:
  ad_address: "172.16.16.9"
  controllerName: "WIFI_A1"
  ssid: "Ph0-WiFi-0"
  hostapd_config: "ap0_hostapd.conf"
  wpa_supplicant_config: "sta0_wpa_supplicant.conf"
  ap0_iface: "wlan1"
  sta0_iface: "wlan1"

controller:
    name: "OBSS_Management_Solution"
    info: "Overlaping BSS Management WiSHFUL Controller"
    dl: "tcp://172.16.16.9:8990"
    ul: "tcp://172.16.16.9:8989"

modules:
    discovery:
        module : wishful_module_discovery_pyre
        class_name : PyreDiscoveryControllerModule
        kwargs: {"iface":"eth0", "groupName":"wifi_warmup_wifi_0", "downlink":"tcp://172.16.16.9:8990", "uplink":"tcp://172.16.16.9:8989"}
