## WiSHFUL Agent config file

agent_info:
  name: 'agent_123'
  info: 'agent_info'
  iface: 'eth0'

modules:
  discovery:
      module : wishful_module_discovery_pyre
      class_name : PyreDiscoveryAgentModule
      kwargs: {"iface":"eth0", "groupName":"wishful_1234"}

  simple:
      module : wishful_module_spectral_scan_ath9k
      class_name : SpectralScanAth9kModule
      interfaces : ['wlan0']

  iperf:
      module : wishful_module_iperf
      class_name : IperfModule

##  rule_manager:
##      module : wishful_module_rules
##      class_name : RuleManagerModule
