## WiSHFUL Controller's config file

controller:
    name: "Controller"
    info: "WiSHFUL Controller"
    dl: "tcp://192.168.1.157:8990"
    ul: "tcp://192.168.1.157:8989"

modules:
    discovery:
        module : wishful_module_discovery_pyre
        class_name : PyreDiscoveryControllerModule
        kwargs: {"iface":"em0", "groupName":"wishful_1234", "downlink":"tcp://192.168.1.157:8990", "uplink":"tcp://192.168.1.157:8989"}
