## WiSHFUL Agent config file

# Agent info structure contains information about agent:
#   -name - name of agent, that can be used to select proper agent by name in control progam.
#           If not set, the name of agent is the same as hostname of node that runs the agent
#   - info - additional information about agent, that can be used to carry some data
#            By default this field is empty
#   - iface - name of interface, which the agent will use to communicate with controller
agent_info:
  name: 'wishful_simple_agent'
  info: 'wishful_simple_agent_info'
  iface: 'eth0'


# List of modules that agent will load during its start
modules:
  # Name of module that will be used in agent
  discovery:
      # Discovery module provides an agent with URLs, which the agent uses to connect to controller
      # module is name of Python module that has to be imported
      module : wishful_module_static_discovery
      # class_name is the name of class from module that Agent has to create and load 
      class_name : StaticDiscoveryModule
      # kwargs contains agruments that will be passed to constructor of class.
      # The argument list depends on module implementation.
      kwargs: {"downlink":"tcp://127.0.0.1:8990", "uplink":"tcp://127.0.0.1:8989"}

  # Name of module that will be used in agent
  ath9k:
      # Ath9k module implements translation of UPI into native interface of Atheros WiFi device
      # module is name of Python module that has to be imported
      module : wishful_module_wifi_ath
      # class_name is the name of class from module that Agent has to create and load 
      class_name : Ath9kModule
      # interfaces is a list of interfaces that will be controlled by ath9k module
      interfaces : ['wlan0']
