#!/usr/bin/env python3
# -*- coding: utf-8 -*-

"""
wishful_agent_simple.py: First implementation of WiSHFUL agent

Usage:
   wishful_agent_simple.py [options] [-q | -v]

Options:
   --logfile name      Name of the logfile
   --config configFile Config file path

Example:
   ./wishful_agent_simple -v --config ./config.yaml

Other options:
   -h, --help          show this help message and exit
   -q, --quiet         print less text
   -v, --verbose       print more text
   --version           show version and exit
"""

import logging
import signal
import sys, os
import yaml
import wishful_agent

__author__ = "Piotr Gawlowicz, Mikolaj Chwalisz"
__copyright__ = "Copyright (c) 2015, Technische Universität Berlin"
__version__ = "0.1.0"
__email__ = "{gawlowicz, chwalisz}@tkn.tu-berlin.de"

# Define logger
log = logging.getLogger('wishful_agent.main')
# Create Agent
agent = wishful_agent.Agent()

def main(args):
    log.debug(args)

    # Load config file
    config_file_path = args['--config']

    config = None
    with open(config_file_path, 'r') as f:
        config = yaml.load(f)

    # Configure and start Agent
    agent.load_config(config)
    agent.run()


if __name__ == "__main__":
    try:
        from docopt import docopt
    except:
        print("""
        Please install docopt using:
            pip install docopt==0.6.1
        For more refer to:
        https://github.com/docopt/docopt
        """)
        raise

    args = docopt(__doc__, version=__version__)

    # Configure logging subsystem with parameters given in cmd
    log_level = logging.INFO  # default
    if args['--verbose']:
        log_level = logging.DEBUG
    elif args['--quiet']:
        log_level = logging.ERROR

    # Configure logging file, if given in cmd
    logfile = None
    if args['--logfile']:
        logfile = args['--logfile']

    logging.basicConfig(filename=logfile, level=log_level,
        format='%(asctime)s - %(name)s.%(funcName)s() - %(levelname)s - %(message)s')

    try:
        # Start Agent loop
        main(args)
    except KeyboardInterrupt:
        # Exit Agent when Ctrl-C is pressed
        log.debug("Agent exits")
    finally:
        # Always stop agent
        log.debug("Exit")
        agent.stop()
