#!/usr/bin/env python3
# -*- coding: utf-8 -*-

"""
wishful_controller_simple.py: First implementation of WiSHFUL controller

Usage:
   wishful_controller_simple.py [options] [-q | -v]

Options:
   --logfile name      Name of the logfile
   --config configFile Config file path

Example:
   ./wishful_simple_local_controller -v --config ./config.yaml 

Other options:
   -h, --help          show this help message and exit
   -q, --quiet         print less text
   -v, --verbose       print more text
   --version           show version and exit
"""

import sys
import datetime
import logging
import gevent
import yaml
import time

sys.path.append('../../../')
sys.path.append("../../../agent_modules/wifi_ath")
sys.path.append("../../../agent_modules/wifi_wmp")
sys.path.append("../../../agent_modules/wifi")
sys.path.append('../../../upis')
sys.path.append('../../../framework')
sys.path.append('../../../agent')
sys.path.append('../../../controller')

sys.path.append('../../../controller_modules')
sys.path.append('../../../controller_modules/wireless_topology')

import wishful_upis as upis
import wishful_controller

from examples.wmp.wmp_radio_program.wmp_helper.controller_utils import *
from examples.wmp.wmp_radio_program.wmp_helper.TestbedTopology import TestbedTopology
from agent_modules.wifi_wmp.wmp_structure import UPI_R


# from wishful_upis.radio import radio_info_t
# from wishful_upis.radio import radio_program_t

import wishful_framework.upi_arg_classes.edca as edca


__author__ = "Domenico Garlisi"
__copyright__ = "Copyright (c) 2015, Technische Universität Berlin"
__version__ = "0.1.0"
__email__ = "{domenico.garlisi@cnit.it"


log = logging.getLogger('wishful_agent.main')
controller = wishful_controller.Controller()
mytestbed = TestbedTopology("wmp_radio_program", log)

# params
# iface to use
wlan_iface = 'wlan0'
wlan_inject_iface = 'wlan0'

nodes = []

@controller.new_node_callback()
def new_node(node):
    print("New node appeared:")
    print(node)
    nodes.append(node)
    mytestbed.add_wmp_node(node, 'STA')

@controller.node_exit_callback()
def node_exit(node, reason):
    if node in nodes:
        nodes.remove(node);
    print("NodeExit : NodeID : {} Reason : {}".format(node.id, reason))


@controller.set_default_callback()
def default_callback(group, node, cmd, data):
    print("DEFAULT CALLBACK : Group: {}, NodeId: {}, Cmd: {}, Returns: {}".format(group, node.id, cmd, data))



def perform_hidden_node_detection(nodes, CSmat, CRmat):
    log.debug("perform_hidden_node_detection")


def main(args):


    log.debug(args)

    config_file_path = args['--config']
    config = None
    with open(config_file_path, 'r') as f:
        config = yaml.load(f)

    controller.load_config(config)

    controller.add_module(moduleName="wireless_topology", pyModuleName="wishful_module_wireless_topology",
                          className="WirelessTopologyModule", importAs="wireless_topology")

    controller.start()

    nodes_platform_info = []
    #control loop
    while True:
        gevent.sleep(10)
        print("\n")
        print("Connected nodes", [str(node.name) for node in nodes])
        if len(nodes) > 1:

            break

    #run execution engine
    mytestbed.initializeTestbedFunctions(controller)

    log.debug(" ... done: %s" % str(nodes))

    # CS test
    log.debug("Testing carrier sensing ...")
    CSmat = controller.blocking(True).wireless_topology.estimate_nodes_in_carrier_sensing_range(nodes, wlan_inject_iface, TAU=0.9)
    log.debug("done ... %s" % str(CSmat))

    # CR test
    log.debug("Testing communication range ...")
    CRmat = controller.blocking(True).wireless_topology.estimate_nodes_in_communication_range(nodes, wlan_inject_iface, MINPDR=0.9)
    log.debug("done ... %s" % str(CRmat))

    # HN detection
    perform_hidden_node_detection(nodes, CSmat, CRmat)



if __name__ == "__main__":
    try:
        from docopt import docopt
    except:
        print("""
        Please install docopt using:
            pip install docopt==0.6.1
        For more refer to:
        https://github.com/docopt/docopt
        """)
        raise

    args = docopt(__doc__, version=__version__)




    log_level = logging.INFO  # default
    if args['--verbose']:
        log_level = logging.DEBUG
    elif args['--quiet']:
        log_level = logging.ERROR

    logfile = None
    if args['--logfile']:
        logfile = args['--logfile']

    logging.basicConfig(filename=logfile, level=log_level,
        format='%(asctime)s - %(name)s.%(funcName)s() - %(levelname)s - %(message)s')

    try:
        main(args)
    except KeyboardInterrupt:
        log.debug("Controller exits")
    finally:
        log.debug("Exit")
        controller.stop()