#!/usr/bin/python

import sys, socket
import time

def main(args):
    ip = args[1]
    port = int(args[2])
    sock = socket.socket(socket.AF_INET, socket.SOCK_DGRAM)
    message = "Light Emitting Diodes are driving a revolution in lighting systems due to their superior energy efficiency and are already entering the Internet of Things (IoT) market with embedded"
    i=0
    
    #while 1:
    #while i<10000:
    for i in range(10000):
        i += 1
        #fp = open(file, 'r')
        #for line in fp:
        #print("MESSAGE: %s" % message)
        sock.sendto(message.encode('utf-8'), (ip, port))
        #sock.close()
        #fp.close()
        #time.sleep(0.05)

main(sys.argv)
