## WiSHFUL Agent config file

agent_info:
  name: 'wishful_simple_agent_123'
  info: 'wishful_simple_agent_info'
  iface: 'eth0'

modules:

  discovery:
      module : wishful_module_discovery_pyre
      class_name : PyreDiscoveryAgentModule
      kwargs: {"iface":"eth0", "groupName":"wishful_1234"}

  wifi:
      module : wishful_module_wifi_wmp
      class_name : WmpModule
      interfaces : ['wlan0']


