## WiSHFUL Controller's config file

parameters:
  ad_address: "172.16.16.9"
  controllerName: "NON_WISHFUL_LTE_U"

controller:
    name: "Non-WiSHFUL LTE-U BS"
    info: "Non-WiSHFUL LTE-U BS"
    dl: "tcp://172.16.16.2:8990"
    ul: "tcp://172.16.16.2:8989"
