## WiSHFUL Controller's config file

controller:
    name: "Controller nova"
    info: "WiSHFUL Controller"
    dl: "tcp://10.8.8.21:8990"
    ul: "tcp://10.8.8.21:8989"

modules:
    discovery:
        module : wishful_module_discovery_pyre
        class_name : PyreDiscoveryControllerModule
        kwargs: {"iface":"eth2", "groupName":"wishful_1234", "downlink":"tcp://10.8.8.21:8990", "uplink":"tcp://10.8.8.21:8989"}

