## WiSHFUL Controller's config file

controller:
    name: "Controller server"
    info: "WiSHFUL Controller"
    dl: "tcp://172.16.0.100:8990"
    ul: "tcp://172.16.0.100:8989"

modules:
    discovery:
        module : wishful_module_discovery_pyre
        class_name : PyreDiscoveryControllerModule
        kwargs: {"iface":"eth4", "groupName":"wishful_1234", "downlink":"tcp://172.16.0.100:8990", "uplink":"tcp://172.16.0.100:8989"}

